language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy3"
env: TEST_RUNNER=pytest
matrix:
  include:
    - python: "3.2"
      env: TEST_RUNNER=py.test
    - python: "3.3"
      env: TEST_RUNNER=py.test
        
install:
  - pip install -r requirements.txt
script:
  - $TEST_RUNNER

